/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

/**
 *
 * @author valentin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelType = new javax.swing.JPanel();
        labelType = new javax.swing.JLabel();
        listeType = new javax.swing.JComboBox();
        boutonAjoutType = new javax.swing.JButton();
        panelFiltres = new javax.swing.JPanel();
        labelFiltres = new javax.swing.JLabel();
        listeFiltres = new javax.swing.JComboBox();
        boutonSuppressionFiltres = new javax.swing.JButton();
        panelRecherche = new javax.swing.JPanel();
        champRecherche = new javax.swing.JTextField();
        boutonRecherche = new javax.swing.JButton();
        panelFacet = new javax.swing.JPanel();
        panelResultats = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelType.setLayout(new java.awt.GridLayout(3, 1));

        labelType.setText("Type");
        panelType.add(labelType);

        listeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelType.add(listeType);

        boutonAjoutType.setText("Ajouter type");
        panelType.add(boutonAjoutType);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(panelType, gridBagConstraints);

        panelFiltres.setLayout(new java.awt.GridLayout(3, 1));

        labelFiltres.setText("Filtres actifs");
        panelFiltres.add(labelFiltres);

        listeFiltres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFiltres.add(listeFiltres);

        boutonSuppressionFiltres.setText("Supprimer filtre");
        panelFiltres.add(boutonSuppressionFiltres);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(panelFiltres, gridBagConstraints);

        panelRecherche.setLayout(new java.awt.GridLayout(1, 2));

        champRecherche.setText("jTextField1");
        panelRecherche.add(champRecherche);

        boutonRecherche.setText("jButton3");
        panelRecherche.add(boutonRecherche);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        getContentPane().add(panelRecherche, gridBagConstraints);

        javax.swing.GroupLayout panelFacetLayout = new javax.swing.GroupLayout(panelFacet);
        panelFacet.setLayout(panelFacetLayout);
        panelFacetLayout.setHorizontalGroup(
            panelFacetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelFacetLayout.setVerticalGroup(
            panelFacetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(panelFacet, gridBagConstraints);

        javax.swing.GroupLayout panelResultatsLayout = new javax.swing.GroupLayout(panelResultats);
        panelResultats.setLayout(panelResultatsLayout);
        panelResultatsLayout.setHorizontalGroup(
            panelResultatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelResultatsLayout.setVerticalGroup(
            panelResultatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(panelResultats, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAjoutType;
    private javax.swing.JButton boutonRecherche;
    private javax.swing.JButton boutonSuppressionFiltres;
    private javax.swing.JTextField champRecherche;
    private javax.swing.JLabel labelFiltres;
    private javax.swing.JLabel labelType;
    private javax.swing.JComboBox listeFiltres;
    private javax.swing.JComboBox listeType;
    private javax.swing.JPanel panelFacet;
    private javax.swing.JPanel panelFiltres;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JPanel panelResultats;
    private javax.swing.JPanel panelType;
    // End of variables declaration//GEN-END:variables
}
