/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;
import java.awt.Color;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JTextArea;

import java.awt.GridBagLayout;
import javax.swing.JScrollBar;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JTextPane;

/**
 *
 * @author valentin
 */
public class FrameDBPedia extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public FrameDBPedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelType = new JPanel();
        labelType = new JLabel();
        panelResultats = new javax.swing.JPanel();
        JScrollBar vbar = new JScrollBar(JScrollBar.VERTICAL, 30, 20, 0, 300);
        listeType = new JComboBox<String>();
        JTextArea textFiltresAjoutes = new JTextArea();
        textFiltresAjoutes.setEditable(false);

        
        boutonAjoutType = new javax.swing.JButton();
        boutonAjoutType.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		String temp = listeType.getSelectedItem().toString();
        		//textTypesAjoutes.append(temp+"\r\n");
        	}
        });
        panelFiltres = new javax.swing.JPanel();
        labelFiltres = new javax.swing.JLabel();
        listeFiltres = new javax.swing.JComboBox();
        boutonSuppressionFiltres = new javax.swing.JButton();
        boutonSuppressionFiltres.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		String temp = listeFiltres.getSelectedItem().toString();
        		textFiltresAjoutes.append(temp+"\r\n");
        	}
        });
        panelRecherche = new javax.swing.JPanel();
        champRecherche = new javax.swing.JTextField();
        champRecherche.setForeground(Color.GRAY);
        boutonRecherche = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        GridBagLayout gridBagLayout = new GridBagLayout();
        gridBagLayout.columnWeights = new double[]{1.0, 0.0};
        gridBagLayout.rowWeights = new double[]{0.0, 0.0, 1.0};
        getContentPane().setLayout(gridBagLayout);

        panelType.setLayout(new java.awt.GridLayout(3, 1));

        labelType.setText("Type");
        panelType.add(labelType);

        listeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelType.add(listeType);

        

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new Insets(0, 0, 5, 5);
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(panelType, gridBagConstraints);

        panelFiltres.setLayout(new java.awt.GridLayout(3, 1));

        labelFiltres.setText("Filtres actifs");
        panelFiltres.add(labelFiltres);

        listeFiltres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFiltres.add(listeFiltres);

        boutonSuppressionFiltres.setText("Supprimer filtre");
        panelFiltres.add(boutonSuppressionFiltres);

        gridBagConstraints_1 = new java.awt.GridBagConstraints();
        gridBagConstraints_1.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_1.gridx = 1;
        gridBagConstraints_1.gridy = 1;
        getContentPane().add(panelFiltres, gridBagConstraints_1);

        panelRecherche.setLayout(new java.awt.GridLayout(1, 2));

        champRecherche.setText("Tapez votre recherche");
        panelRecherche.add(champRecherche);

        boutonRecherche.setText("Rechercher");
        panelRecherche.add(boutonRecherche);

        gridBagConstraints_2 = new java.awt.GridBagConstraints();
        gridBagConstraints_2.insets = new Insets(0, 0, 5, 0);
        gridBagConstraints_2.gridx = 1;
        gridBagConstraints_2.gridy = 0;
        getContentPane().add(panelRecherche, gridBagConstraints_2);
        
        
        
        boutonAjoutType.setText("Ajouter type");
        panelType.add(boutonAjoutType);
        
        
        GridBagConstraints gbc_panel = new GridBagConstraints();
        gbc_panel.insets = new Insets(0, 0, 0, 5);
        gbc_panel.fill = GridBagConstraints.BOTH;
        gbc_panel.gridx = 0;
        gbc_panel.gridy = 2;
        getContentPane().add(panel, gbc_panel);
        
        

        javax.swing.GroupLayout panelResultatsLayout = new javax.swing.GroupLayout(panelResultats);
        panelResultatsLayout.setHorizontalGroup(
        	panelResultatsLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(textFiltresAjoutes, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelResultatsLayout.setVerticalGroup(
        	panelResultatsLayout.createParallelGroup(Alignment.LEADING)
        		.addComponent(textFiltresAjoutes, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelResultats.setLayout(panelResultatsLayout);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(panelResultats, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDBPedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDBPedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDBPedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDBPedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDBPedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAjoutType;
    private javax.swing.JButton boutonRecherche;
    private javax.swing.JButton boutonSuppressionFiltres;
    private javax.swing.JTextField champRecherche;
    private javax.swing.JLabel labelFiltres;
    private javax.swing.JLabel labelType;
    private javax.swing.JComboBox listeFiltres;
    private javax.swing.JComboBox listeType;
    private javax.swing.JPanel panelFiltres;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JPanel panelResultats;
    private javax.swing.JPanel panelType;
    private GridBagConstraints gridBagConstraints_1;
    private GridBagConstraints gridBagConstraints_2;
    private JPanel panel;
}
